
#include "p16f877a.inc"						
LIST P=16F877A								
RADIX HEX

;Variables						
W 		EQU 0X00 
SEGTM 	EQU 0X29		
ORG 0X00

;Banco 1	
BSF 	STATUS, RP0 ;1
BCF 	STATUS, RP1 ;0							

CLRF	TRISB


;Banco 0
BCF 	STATUS, RP0 ;0
BCF 	STATUS, RP1 ;0							
 								
CLRF	PORTB

;Banco 1
BSF 	STATUS, RP0 ;1
BCF 	STATUS, RP1 ;0

MOVLW 	B'11010111'	;Lo Cargo a W					
MOVWF 	OPTION_REG	;Lo muevo de W a OPTION_REG						

;Banco 0
BCF		STATUS, RP0;
MOVLW	B'11111111'
MOVWF	PORTB
CICLO
	CALL  	RETARDO
	MOVFW	SEGTM	;MUEVO MOV de F(SEGTM) a W
	MOVWF 	PORTB	;MUEVO MOV de W a F(SEGTM) 
	ADDLW	0x01	;le sumo 1 a W
	MOVWF	SEGTM	;MUEVO MOV de W a F(SEGTM) 
	SUBLW	0x3C	;LE RESTO 60(3C) a W 
	BTFSC	STATUS,Z	;SI W es 0 entonces 
		CLRF	SEGTM	;LIMPIO EL REGISTRO SEGTM (MIVARIABLE)
	
	
		
	
GOTO	CICLO

;Subrutinas de retardo de 1 Segundo
RETARDO	;256-(500/255)=
		;256-(100/((4/1000)*256)=255
		BCF 	INTCON,TMR0IF
		MOVLW	D'255'
		MOVWF 	TMR0
		COMPROBAR 
			BTFSS INTCON,TMR0IF ;
			GOTO COMPROBAR
		RETURN


END